ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
IMAGEN = "alvistack/ubuntu-24.04"
HOSTNAME = "test.home.local"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/home/vagrant", type: "rsync", disabled: true
  # config.vm.network "forwarded_port", guest: 5433, host: 5433 ## Exponer el puerto 5433 en host local

  config.vm.define :server do |s|
    s.vm.box = IMAGEN
    s.vm.hostname = HOSTNAME
    s.vm.provision :docker
    s.vm.provision :docker_compose
    s.vm.provision "shell", path: "install_terraform.sh"

    s.vm.provider :libvirt do |v|
      v.memory = 2048
      v.cpus = 2
      v.disk_bus = "virtio"
      v.graphics_type = "none"
    end
  end
end
